platform :ios, '7.0'
target 'OCTest' do
    pod 'AFNetworking', '~> 2.5.0'
    pod 'STAlertView', '~> 1.0.0'
end
target 'OCTestTests' do
    pod 'AFNetworking', '~> 2.5.0'
    pod 'STAlertView', '~> 1.0.0'
    pod 'Kiwi', '~> 2.4.0'
end